CREATE DATABASE EDT;
USE EDT;



CREATE TABLE "EmploiDuTemps" (
id INTEGER IDENTITY PRIMARY KEY NOT NULL,
dateDebut DATETIME,
dateFin DATETIME
);


CREATE TABLE "Cours" (
id INTEGER IDENTITY PRIMARY KEY NOT NULL,
dateDebut DATETIME,
dateFin DATETIME,
idEmploiDuTemps INTEGER FOREIGN KEY REFERENCES EmploiDuTemps(id),
);


CREATE TABLE "Formation"(
id INTEGER IDENTITY NOT NULL PRIMARY KEY,
nom VARCHAR(50),
nbHeuresTotal NUMERIC(4,1)
);

CREATE TABLE "Promotion"(
id INTEGER IDENTITY PRIMARY KEY NOT NULL,
nom VARCHAR(50),
dateDebut DATE,
dateFin DATE,
idformation INTEGER NOT NULL FOREIGN KEY REFERENCES Formation(id),
idCours INTEGER FOREIGN KEY REFERENCES Cours(id)
);

CREATE TABLE "Eleve"(
id INTEGER IDENTITY PRIMARY KEY NOT NULL,     
nom VARCHAR(50) ,
Prenom VARCHAR(50),
mail VARCHAR(50),
idPromotion INTEGER FOREIGN KEY REFERENCES Promotion(id) NOT NULL,
);


CREATE TABLE "Matiere" (
id INTEGER IDENTITY PRIMARY KEY NOT NULL,
nom VARCHAR(50),
idCours INTEGER FOREIGN KEY REFERENCES Cours(id)
);

CREATE TABLE "Formation_Matiere"(
idFormation INTEGER NOT NULL FOREIGN KEY REFERENCES Formation(id),
idMatiere INTEGER NOT NULL FOREIGN KEY REFERENCES Matiere(id),
PRIMARY KEY (idFormation,idMatiere)

);


CREATE TABLE "Formateur" (
id INTEGER IDENTITY PRIMARY KEY NOT NULL,
nom VARCHAR(50),
prenom VARCHAR(50),
mail VARCHAR(50),
telephone VARCHAR(10),
idCours INTEGER FOREIGN KEY REFERENCES Cours(id) NULL
);

CREATE TABLE "Formateur_Matiere"(
idFormateur INTEGER NOT NULL FOREIGN KEY REFERENCES Formateur(id),
idMatiere INTEGER NOT NULL FOREIGN KEY REFERENCES Matiere(id),
PRIMARY KEY (idFormateur, idMatiere)
);

CREATE TABLE "Salle"(
id INTEGER IDENTITY PRIMARY KEY NOT NULL,
nom VARCHAR(50),
capacite INTEGER,
idCours INTEGER FOREIGN KEY REFERENCES Cours(id),
);

CREATE TABLE "Absence" (
idEleve INTEGER FOREIGN KEY REFERENCEs Eleve(id),
idcours INTEGER FOREIGN KEY REFERENCES Cours(id),
PRIMARY KEY (idEleve, idCours)

);






















